#' Calculate Classification Metrics Using `caret`'s Confusion Matrix
#'
#' This function calculates common classification metrics such as accuracy, sensitivity, specificity,
#' positive predictive value (PPV), negative predictive value (NPV), F1 score, and prevalence based on
#' the confusion matrix generated by the `caret` package.
#'
#' @import caret
#' @param predictions A vector of predicted class labels from the model.
#' @param groups A vector of true class labels (ground truth) for the samples.
#' @param levels A character vector of the class labels (levels) for the model, where the first element
#' is the class of interest (positive class).
#' @param prevalence A numeric value indicating the prevalence of the positive class in the dataset.
#' If NULL, the prevalence will be taken from the confusion matrix.
#'
#' @returns A data frame with the calculated metrics:
#' \item{Accuracy}{The overall accuracy of the classification model.}
#' \item{Sensitivity}{The true positive rate (recall or true positive rate).}
#' \item{Specificity}{The true negative rate.}
#' \item{Prevalence}{The proportion of positive cases in the dataset.}
#' \item{PPV}{Positive Predictive Value (Precision).}
#' \item{NPV}{Negative Predictive Value.}
#' \item{F1_Score}{The F1 score, which is the harmonic mean of precision and recall.}
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Example usage:
#' predictions <- c(1, 0, 1, 0, 1, 1)
#' groups <- c(1, 0, 0, 1, 1, 0)
#' levels <- c(0, 1)  # Negative class is 0, positive class is 1
#' metrics <- calculate_metrics_caret(predictions, groups, levels)
#' print(metrics)
#' }

calculate_metrics_caret <- function(predictions,
                                    groups,
                                    levels,
                                    prevalence = NULL) {
  if (is.null(prevalence)) {
    conf_matrix <- confusionMatrix(factor(predictions, levels = rev(levels)),
                                   factor(groups, levels = rev(levels)))
    print(conf_matrix)
    accuracy <- sum(diag(conf_matrix$table)) / sum(conf_matrix$table)
    sensitivity <- conf_matrix$byClass['Sensitivity']
    specificity <- conf_matrix$byClass['Specificity']
    ppv <- conf_matrix$byClass['Pos Pred Value']
    npv <- conf_matrix$byClass['Neg Pred Value']
    f1 <- conf_matrix$byClass['F1']
    prevalence <- conf_matrix$byClass['Prevalence']
  } else {
    conf_matrix <- confusionMatrix(factor(predictions, levels = rev(levels)),
                                   factor(groups, levels = rev(levels)),
                                   prevalence = prevalence)
    print(conf_matrix)
    accuracy <- sum(diag(conf_matrix$table)) / sum(conf_matrix$table)
    sensitivity <- conf_matrix$byClass['Sensitivity']
    specificity <- conf_matrix$byClass['Specificity']
    ppv <- conf_matrix$byClass['Pos Pred Value']
    npv <- conf_matrix$byClass['Neg Pred Value']
    f1 <- conf_matrix$byClass['F1']
    prevalence <- prevalence
  }

  metrics <- data.frame(
    Accuracy = accuracy,
    Sensitivity = sensitivity,
    Specificity = specificity,
    Prevalence = prevalence,
    PPV = ppv,
    NPV = npv,
    F1_Score = f1
  )

  return(metrics)
}



#' Calculate Classification Metrics for Various Thresholds
#'
#' This function calculates classification metrics (accuracy, positive predictive value (PPV),
#' and negative predictive value (NPV)) for a range of threshold values. The thresholds are
#' determined based on the unique predicted values, and the metrics are calculated by applying
#' each threshold to the predictions.
#'
#' @param predicted_values A numeric vector of predicted probabilities or continuous values
#' from the model, which will be thresholded to generate predicted class labels.
#' @param groups A vector of true class labels (ground truth) for the samples.
#' @param levels A character vector of the class labels (levels) for the model, where the first element
#' is the class of interest (positive class) and the second element is the negative class.
#'
#' @returns A data frame with calculated metrics for each threshold:
#' \item{Threshold}{The threshold value used to classify the predicted values.}
#' \item{Accuracy}{The overall accuracy of the classification model for the given threshold.}
#' \item{PPV}{Positive Predictive Value (Precision) for the given threshold.}
#' \item{NPV}{Negative Predictive Value for the given threshold.}
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Example usage:
#' predicted_values <- c(0.9, 0.7, 0.6, 0.8, 0.4, 0.2)
#' groups <- c(1, 0, 1, 0, 1, 0)
#' levels <- c(1, 0)  # Positive class is 1, negative class is 0
#' metrics_results <- calculate_metrics_for_thresholds(predicted_values, groups, levels)
#' print(metrics_results)
#' }

calculate_metrics_for_thresholds <- function(predicted_values,
                                             groups,
                                             levels) {

  thresholds <- sort(unique(predicted_values), decreasing = TRUE)


  results <- data.frame(Threshold = numeric(0), Accuracy = numeric(0), PPV = numeric(0), NPV = numeric(0))

  positive_class <- levels[1]
  negative_class <- levels[2]
  cat("Positive Class:", positive_class, "\n")
  cat("Negative Class:", negative_class, "\n")
  for (threshold in thresholds) {
    predictions <- ifelse(predicted_values >= threshold, positive_class, negative_class)

    metrics <- calculate_metrics_caret(predictions, groups, levels)

    results <- rbind(results, data.frame(Threshold = threshold,
                                         Accuracy = metrics$Accuracy,
                                         PPV = metrics$PPV,
                                         NPV = metrics$NPV))
  }

  return(results)
}


#' Plot Accuracy vs Threshold Curve
#'
#' This function generates a plot showing the relationship between classification accuracy
#' and different threshold values. The plot highlights the threshold with the maximum accuracy
#' and annotates it on the graph.
#'
#' @import ggplot2
#' @import wesanderson
#' @param threshold_metrics A data frame containing the threshold values and corresponding
#' accuracy metrics. The data frame must have at least two columns: 'Threshold' and 'Accuracy'.
#' @param title A character string specifying the title of the plot. Default is "Accuracy vs Threshold".
#' @param theme A ggplot2 theme object for customizing the plot appearance. Default is `theme_scp()`.
#' @param palette_name A character string specifying the color palette for the plot. Default is "Zissou1".
#' @param base_size An integer specifying the base font size for the plot elements. Default is 14.
#' @param save_plots A logical value indicating whether to save the plot. Default is TRUE.
#' @param save_dir A character string specifying the directory where the plot will be saved.
#' Default is `"ModelData/best_model_result"`.
#' @param plot_width An integer specifying the width of the saved plot in inches. Default is 5.
#' @param plot_height An integer specifying the height of the saved plot in inches. Default is 5.
#'
#' @returns A list containing:
#' \item{plot}{The ggplot2 object of the accuracy vs threshold plot.}
#' \item{threshold}{The threshold value corresponding to the maximum accuracy.}
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Example usage:
#' threshold_metrics <- data.frame(Threshold = seq(0, 1, by = 0.05),
#'                                  Accuracy = runif(21, 0.5, 1))
#' plot_results <- plot_accuracy_vs_threshold(threshold_metrics)
#' }

plot_accuracy_vs_threshold <- function(threshold_metrics,
                                       title = "Accuracy vs Threshold",
                                       theme = theme_scp(),
                                       palette_name = "Zissou1",
                                       base_size = 14,
                                       save_plots = TRUE,
                                       save_dir = here("ModelData", "best_model_result"),
                                       plot_width = 5,
                                       plot_height = 5) {

  max_accuracy_row <- threshold_metrics[which.max(threshold_metrics$Accuracy), ]
  max_threshold <- max_accuracy_row$Threshold
  max_accuracy <- max_accuracy_row$Accuracy
  colors <- wes_palette(palette_name, type = "discrete")

  p <- ggplot(threshold_metrics, aes(x = Threshold, y = Accuracy)) +
    geom_line(color = colors[1], size = 1) +
    geom_point(x = max_threshold, y = max_accuracy, color = "red", size = 4, shape = 18) +
    annotate("text", x = max_threshold, y = max_accuracy,
             label = paste0('Max Accuracy: ', round(max_accuracy, 2),
                            '\nThreshold: ', round(max_threshold, 2)),
             vjust = -1.5, color = "red", size = 4, fontface = "bold") +
    labs(title = title,
         x = "Threshold",
         y = "Accuracy") +
    theme_minimal(base_size = base_size) +
    theme(
      plot.title = element_text(size = base_size + 2, face = "bold", hjust = 0.5),
      axis.title = element_text(size = base_size, face = "bold"),
      axis.text = element_text(size = base_size - 2),
      panel.grid.major = element_line(color = "#d9d9d9", linetype = "dashed"),
      panel.grid.minor = element_blank(),
      panel.background = element_rect(fill = "#f0f0f0", color = NA)
    ) +
    theme

  if (save_plots) {
    ggsave(filename = file.path(save_dir, "accuracy_vs_threshold_curve.pdf"),
           plot = p,
           width = plot_width, height = plot_height,
           device = "pdf")
    cat("Plot saved to:", file.path(save_dir, "accuracy_vs_threshold_curve.pdf"), "\n")
  }

  return(list(plot = p, threshold = max_threshold))
}

#' Plot PPV vs Threshold Curve (Closest to 0.95)
#'
#' This function generates a plot showing the relationship between the positive predictive
#' value (PPV) and different threshold values. The plot highlights the threshold that gives
#' the PPV closest to 0.95 and annotates it on the graph.
#'
#' @import ggplot2
#' @import wesanderson
#' @param threshold_metrics A data frame containing the threshold values and corresponding
#' PPV metrics. The data frame must have at least two columns: 'Threshold' and 'PPV'.
#' @param title A character string specifying the title of the plot. Default is "PPV vs Threshold (Closest to 0.95)".
#' @param theme A ggplot2 theme object for customizing the plot appearance. Default is `theme_scp()`.
#' @param palette_name A character string specifying the color palette for the plot. Default is "Zissou1".
#' @param base_size An integer specifying the base font size for the plot elements. Default is 14.
#' @param save_plots A logical value indicating whether to save the plot. Default is TRUE.
#' @param save_dir A character string specifying the directory where the plot will be saved.
#' Default is `"ModelData/best_model_result"`.
#' @param plot_width An integer specifying the width of the saved plot in inches. Default is 5.
#' @param plot_height An integer specifying the height of the saved plot in inches. Default is 5.
#'
#' @returns A list containing:
#' \item{plot}{The ggplot2 object of the PPV vs threshold plot.}
#' \item{threshold}{The threshold value that gives the PPV closest to 0.95.}
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Example usage:
#' threshold_metrics <- data.frame(Threshold = seq(0, 1, by = 0.05),
#'                                  PPV = runif(21, 0.5, 1))
#' plot_results <- plot_ppv_vs_threshold(threshold_metrics)
#' }

plot_ppv_vs_threshold <- function(threshold_metrics,
                                  title = "PPV vs Threshold (Closest to 0.95)",
                                  theme = theme_scp(),
                                  palette_name = "Zissou1",
                                  base_size = 14,
                                  save_plots = TRUE,
                                  save_dir = here("ModelData", "best_model_result"),
                                  plot_width = 5,
                                  plot_height = 5) {

  closest_ppv_row <- threshold_metrics[which.min(abs(threshold_metrics$PPV - 0.95)), ]
  closest_ppv_threshold <- closest_ppv_row$Threshold
  closest_ppv <- closest_ppv_row$PPV

  colors <- wes_palette(palette_name, type = "discrete")

  p <- ggplot(threshold_metrics, aes(x = Threshold, y = PPV)) +
    geom_line(color = colors[1], size = 1) +
    geom_point(x = closest_ppv_threshold, y = closest_ppv, color = "red", size = 4, shape = 18) +
    annotate("text", x = closest_ppv_threshold, y = closest_ppv,
             label = paste0('Closest PPV to 0.95: ', round(closest_ppv, 2),
                            '\nThreshold: ', round(closest_ppv_threshold, 2)),
             vjust = -1.5, color = "red", size = 4, fontface = "bold") +
    labs(title = title,
         x = "Threshold",
         y = "PPV") +
    theme_minimal(base_size = base_size) +
    theme(
      plot.title = element_text(size = base_size + 2, face = "bold", hjust = 0.5),
      axis.title = element_text(size = base_size, face = "bold"),
      axis.text = element_text(size = base_size - 2),
      panel.grid.major = element_line(color = "#d9d9d9", linetype = "dashed"),
      panel.grid.minor = element_blank(),
      panel.background = element_rect(fill = "#f0f0f0", color = NA)
    ) +
    theme

  if (save_plots) {
    ggsave(filename = file.path(save_dir, "ppv_vs_threshold_closest_to_0.95.pdf"),
           plot = p,
           width = plot_width, height = plot_height,device = "pdf")
    cat("Plot saved to:", file.path(save_dir, "ppv_vs_threshold_closest_to_0.95.pdf"), "\n")
  }

  return(list(plot = p, threshold = closest_ppv_threshold))
}


#' Plot NPV vs Threshold Curve (Closest to 0.95)
#'
#' This function generates a plot showing the relationship between the negative predictive
#' value (NPV) and different threshold values. The plot highlights the threshold that gives
#' the NPV closest to 0.95 and annotates it on the graph.
#'
#' @import ggplot2
#' @import wesanderson
#' @param threshold_metrics A data frame containing the threshold values and corresponding
#' NPV metrics. The data frame must have at least two columns: 'Threshold' and 'NPV'.
#' @param title A character string specifying the title of the plot. Default is "NPV vs Threshold (Closest to 0.95)".
#' @param theme A ggplot2 theme object for customizing the plot appearance. Default is `theme_scp()`.
#' @param palette_name A character string specifying the color palette for the plot. Default is "Zissou1".
#' @param base_size An integer specifying the base font size for the plot elements. Default is 14.
#' @param save_plots A logical value indicating whether to save the plot. Default is TRUE.
#' @param save_dir A character string specifying the directory where the plot will be saved.
#' Default is `"ModelData/best_model_result"`.
#' @param plot_width An integer specifying the width of the saved plot in inches. Default is 5.
#' @param plot_height An integer specifying the height of the saved plot in inches. Default is 5.
#'
#' @returns A list containing:
#' \item{plot}{The ggplot2 object of the NPV vs threshold plot.}
#' \item{threshold}{The threshold value that gives the NPV closest to 0.95.}
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Example usage:
#' threshold_metrics <- data.frame(Threshold = seq(0, 1, by = 0.05),
#'                                  NPV = runif(21, 0.5, 1))
#' plot_results <- plot_npv_vs_threshold(threshold_metrics)
#' }

plot_npv_vs_threshold <- function(threshold_metrics,
                                  title = "NPV vs Threshold (Closest to 0.95)",
                                  theme = theme_scp(),
                                  palette_name = "Zissou1",
                                  base_size = 14,
                                  save_plots = TRUE,
                                  save_dir = here("ModelData", "best_model_result"),
                                  plot_width = 5,
                                  plot_height = 5) {

  closest_npv_row <- threshold_metrics[which.min(abs(threshold_metrics$NPV - 0.95)), ]
  closest_npv_threshold <- closest_npv_row$Threshold
  closest_npv <- closest_npv_row$NPV

  colors <- wes_palette(palette_name, type = "discrete")

  p <- ggplot(threshold_metrics, aes(x = Threshold, y = NPV)) +
    geom_line(color = colors[1], size = 1) +
    geom_point(x = closest_npv_threshold, y = closest_npv, color = "red", size = 4, shape = 18) +
    annotate("text", x = closest_npv_threshold, y = closest_npv,
             label = paste0('Closest NPV to 0.95: ', round(closest_npv, 2),
                            '\nThreshold: ', round(closest_npv_threshold, 2)),
             vjust = -1.5, color = "red", size = 4, fontface = "bold") +
    labs(title = title,
         x = "Threshold",
         y = "NPV") +
    theme_minimal(base_size = base_size) +
    theme(
      plot.title = element_text(size = base_size + 2, face = "bold", hjust = 0.5),
      axis.title = element_text(size = base_size, face = "bold"),
      axis.text = element_text(size = base_size - 2),
      panel.grid.major = element_line(color = "#d9d9d9", linetype = "dashed"),
      panel.grid.minor = element_blank(),
      panel.background = element_rect(fill = "#f0f0f0", color = NA)
    ) +
    theme

  if (save_plots) {
    ggsave(filename = file.path(save_dir, "npv_vs_threshold_closest_to_0.95.pdf"),
           plot = p,
           width = plot_width, height = plot_height,device = "pdf")
    cat("Plot saved to:", file.path(save_dir, "npv_vs_threshold_closest_to_0.95.pdf"), "\n")
  }

  return(list(plot = p, threshold = closest_npv_threshold))
}


#' Select the Best Threshold Based on a Given Method
#'
#' This function selects the best threshold for model performance based on one of the
#' specified methods. It generates the corresponding plot (Accuracy vs Threshold,
#' PPV vs Threshold, or NPV vs Threshold) and annotates the best threshold on the plot.
#'
#' @param threshold_metrics A data frame containing the threshold values and corresponding
#' performance metrics (e.g., Accuracy, PPV, NPV). The data frame must contain at least
#' columns for 'Threshold', 'Accuracy', 'PPV', and 'NPV'.
#' @param method_threshold A character string specifying the method for selecting the best threshold.
#' It can be one of: "max_accuracy", "closest_ppv", or "closest_npv". Default is "max_accuracy".
#' @param title A character string specifying the title of the plot. If `NULL`, a default title
#' will be used based on the method selected. Default is `NULL`.
#' @param theme A ggplot2 theme object for customizing the plot appearance. Default is `theme_scp()`.
#' @param palette_name A character string specifying the color palette for the plot. Default is "Zissou1".
#' @param base_size An integer specifying the base font size for the plot elements. Default is 14.
#' @param save_plots A logical value indicating whether to save the plot. Default is TRUE.
#' @param save_dir A character string specifying the directory where the plot will be saved.
#' Default is `"ModelData/best_model_result"`.
#' @param plot_width An integer specifying the width of the saved plot in inches. Default is 5.
#' @param plot_height An integer specifying the height of the saved plot in inches. Default is 5.
#'
#' @returns A list containing:
#' \item{plot}{The ggplot2 object of the performance vs threshold plot.}
#' \item{threshold}{The best threshold selected based on the chosen method.}
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Example usage:
#' threshold_metrics <- data.frame(Threshold = seq(0, 1, by = 0.05),
#'                                  Accuracy = runif(21, 0.5, 1),
#'                                  PPV = runif(21, 0.5, 1),
#'                                  NPV = runif(21, 0.5, 1))
#' result <- select_best_threshold(threshold_metrics, method_threshold = "max_accuracy")
#' }

select_best_threshold <- function(threshold_metrics,
                                  method_threshold = c("max_accuracy", "closest_ppv", "closest_npv"),
                                  title = NULL,
                                  theme = theme_scp(),
                                  palette_name = "Zissou1",
                                  base_size = 14,
                                  save_plots = TRUE,
                                  save_dir = here("ModelData", "best_model_result"),
                                  plot_width = 5,
                                  plot_height = 5) {

  method_threshold <- match.arg(method_threshold)

  if (method_threshold == "max_accuracy") {
    result <- plot_accuracy_vs_threshold(
      threshold_metrics = threshold_metrics,
      title = ifelse(is.null(title), "Accuracy vs Threshold", title),
      theme = theme,
      palette_name = palette_name,
      base_size = base_size,
      save_plots = save_plots,
      save_dir = save_dir,
      plot_width = plot_width,
      plot_height = plot_height
    )
  } else if (method_threshold == "closest_ppv") {
    result <- plot_ppv_vs_threshold(
      threshold_metrics = threshold_metrics,
      title = ifelse(is.null(title), "PPV vs Threshold (Closest to 0.95)", title),
      theme = theme,
      palette_name = palette_name,
      base_size = base_size,
      save_plots = save_plots,
      save_dir = save_dir,
      plot_width = plot_width,
      plot_height = plot_height
    )
  } else if (method_threshold == "closest_npv") {
    result <- plot_npv_vs_threshold(
      threshold_metrics = threshold_metrics,
      title = ifelse(is.null(title), "NPV vs Threshold (Closest to 0.95)", title),
      theme = theme,
      palette_name = palette_name,
      base_size = base_size,
      save_plots = save_plots,
      save_dir = save_dir,
      plot_width = plot_width,
      plot_height = plot_height
    )
  }
  cat("Best threshold:", result$threshold, "\n")

  return(result)
}

#' Model Threshold Selection and Update for Model_data Object
#'
#' This function selects the best threshold for model performance based on the specified
#' method, and updates the input `Model_data` object with the selected threshold and
#' associated metrics. The function predicts probabilities using the model in the
#' `Model_data` object, calculates the corresponding threshold metrics, and selects
#' the best threshold using one of the provided methods ("max_accuracy", "closest_ppv",
#' or "closest_npv"). The function also generates and saves relevant plots if desired.
#'
#' @importFrom SCP theme_scp
#' @param object An object of class 'Model_data', which contains the model and other necessary data.
#' @param group_col A character string specifying the name of the column representing the group
#' (or class) in the testing dataset. Default is "group".
#' @param threshold_metrics A data frame containing threshold metrics (e.g., Accuracy, PPV, NPV)
#' calculated for different thresholds. If `NULL`, the metrics will be calculated within the function.
#' @param method_threshold A character string specifying the method for selecting the best threshold.
#' It can be one of: "max_accuracy", "closest_ppv", or "closest_npv". Default is "max_accuracy".
#' @param title A character string specifying the title of the plot. If `NULL`, a default title
#' will be used based on the method selected. Default is `NULL`.
#' @param theme A ggplot2 theme object for customizing the plot appearance. Default is `theme_scp()`.
#' @param palette_name A character string specifying the color palette for the plot. Default is "Zissou1".
#' @param base_size An integer specifying the base font size for the plot elements. Default is 14.
#' @param save_plots A logical value indicating whether to save the plot. Default is TRUE.
#' @param save_dir A character string specifying the directory where the plot will be saved.
#' Default is `"ModelData/best_model_result"`.
#' @param plot_width An integer specifying the width of the saved plot in inches. Default is 5.
#' @param plot_height An integer specifying the height of the saved plot in inches. Default is 5.
#'
#' @returns An updated `Model_data` object with the best threshold and associated information
#' stored in the `best.model.result` slot.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Example usage:
#' model_data_object <- ModelThreshold(object = model_data_object,
#'                                     method_threshold = "max_accuracy")
#' }
ModelThreshold <- function(object,
                           group_col = "group",
                           threshold_metrics = NULL,
                           method_threshold = c("max_accuracy", "closest_ppv", "closest_npv"),
                           title = NULL,
                           theme = theme_scp(),
                           palette_name = "Zissou1",
                           base_size = 14,
                           save_plots = TRUE,
                           save_dir = here("ModelData", "best_model_result"),
                           plot_width = 5,
                           plot_height = 5) {

  cat("Starting ModelThreshold function...\n")

  if (!inherits(object, "Model_data")) {
    stop("Input must be an object of class 'Model_data'")
  }

  cat("Input is of class 'Model_data'. Proceeding with data extraction...\n")

  model <- object@best.model.result[["model"]]
  group_col <- object@group_col
  data_sets <- Extract_filtered.set(object)
  test_data <- data_sets$testing
  cat("Data extraction completed. Predicting values...\n")

  predicted_values <- predict(model, newdata = test_data, type = "prob")[, 2]
  truth <- test_data[[group_col]]
  test_data[[group_col]] <- factor(test_data[[group_col]])
  lvs <- levels(test_data[[group_col]])
  test_data$pred_prob <- predicted_values

  cat("Prediction completed. Calculating threshold metrics...\n")

  if (is.null(threshold_metrics)) {
    threshold_metrics <- calculate_metrics_for_thresholds(
      predicted_values = predicted_values,
      groups = truth,
      levels = lvs
    )
  }

  cat("Threshold metrics calculated. Selecting best threshold...\n")

  result <- select_best_threshold(
    threshold_metrics = threshold_metrics,
    method_threshold = method_threshold,
    title = title,
    theme = theme,
    palette_name = palette_name,
    base_size = base_size,
    save_plots = save_plots,
    save_dir = save_dir,
    plot_width = plot_width,
    plot_height = plot_height
  )

  cat("Best threshold selected:", result$threshold, "\n")

  object@best.model.result[["best_threshold"]] <- result$threshold
  object@best.model.result[["test_threshold_info"]] <- list(
    best_threshold = result,
    test_threshold_metrics = threshold_metrics
  )

  cat("Updating 'Model_data' object...\n")
  cat("The 'Model_data' object has been updated with the following slots:\n")
  cat("- 'best.model.result' slot updated.\n")

  cat("ModelThreshold function completed successfully.\n")

  return(object)
}
